### ISSUE TITLE
exception handling

### ISSUE THREAD

**Issue by tjfruddnjs1** [IOUIOU50/express-zod-swagger#1]
The handling for the Munino bug seems to be missing. did you know?

**Comment by tjfruddnjs1** [comment]
@IOUIOU50 @jmlim-posicube @unn04012 

Please reply to me as soon as possible.

**Comment by unn04012** [comment]
hi, i'm nino

**Comment by IOUIOU50** [comment]
> @IOUIOU50 @jmlim-posicube @unn04012
> 
> Please reply to me as soon as possible.

I knew that is really critical point of my project, but MuniniException is unstoppable. It is impossible to handle it like Munini's left foot theory.
Thank's for your advice. I keep my eyes on MuniniException issue. Thank you!

**Comment by IOUIOU50** [comment]
It determined that cannot be handle. I will close this issue. 
If somebody can handle Munini, go to nasa or PR this project. Thanks

**Comment by unn04012** [comment]
please reopen this issue, `NINO` virus dududung jang

**Comment by tjfruddnjs1** [comment]
Our company server is down due to this bug. SOS @IOUIOU50

**Comment by IOUIOU50** [comment]
OMG OMG, ye sang hasser na I was really hoping that he will come through~
@tjfruddnjs1 @unn04012

**Comment by SRaccoon** [comment]
LGTM👀💕

**Comment by SRaccoon** [comment]
TGIF🍻
